---
- name: Install Python packages required for gcp_compute_firewall
  become: yes
  package:
    name:
      - python-requests
      - python-google-auth

- name: Open port for SSH
  gcp_compute_firewall:
    name: ssh
    description: Secure Shell
    allowed:
      - ip_protocol: tcp
        ports: ["{{ ssh_port }}"]
    auth_kind: machineaccount
    project: "{{ gcp_project }}"
    service_account_email: "{{ gcp_service_account_email }}"
