---
- name: Change SSH port to {{ ssh_port }}
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^\s*#?\s*Port\s+'
    line: Port {{ ssh_port }}
  notify: Reload SSH config

- name: Configure SELinux
  seport:
    setype: ssh_port_t
    proto: tcp
    ports: "{{ ssh_port }}"
  when:
  - ansible_selinux is defined
  - ansible_selinux|bool
  - ansible_selinux.status == "enabled"

- name: Configure firewalld
  firewalld:
    port: "{{ ssh_port }}/tcp"
    state: enabled
    permanent: yes
    immediate: yes
  # Not all systems have firewalld
  ignore_errors: yes

- name: GCP Firewall
  include_tasks: gcp.yml
  when:
    - gcp_project is defined
    - gcp_service_account_email is defined

- meta: flush_handlers

- name: Validate new SSH port
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ ssh_port }}"
    search_regex: SSH
  delegate_to: localhost
