---
- name: Gathering Service Facts
  service_facts: {}

- name: Change SSH port to {{ ssh_port }}
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^\s*#?\s*Port\s+'
    line: Port {{ ssh_port }}
  notify: Reload SSH config

- name: Configure SELinux
  seport:
    setype: ssh_port_t
    proto: tcp
    ports: "{{ ssh_port }}"
  when:
  - ansible_selinux is defined
  - ansible_selinux|bool
  - ansible_selinux.status == "enabled"

- name: Open port for SSH
  include_role:
    name: bit_kitchen.open_port
  vars:
    open_port: "{{ ssh_port }}"
    open_protocol: tcp

- meta: flush_handlers

- name: Validate new SSH port
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ ssh_port }}"
    search_regex: SSH
  delegate_to: localhost
